// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/occupancy/V1Hierarchy.tsx": () => import("../components/mockups/occupancy/V1Hierarchy.tsx"),
  "./components/mockups/occupancy/V2Affordances.tsx": () => import("../components/mockups/occupancy/V2Affordances.tsx"),
  "./components/mockups/occupancy/V3Accessibility.tsx": () => import("../components/mockups/occupancy/V3Accessibility.tsx")
};
